Debug on function list retire
sysprog21/concurrent-programs pull request #10
Opened 2022-04-23 03:18 UTC by kevinshieh0225

In hp_list project's function : _list_hp_retire_, it attempt to reorganize retire list while the object is deleting.
However, as I see, the origin code doesn't adjust the index simultaneously, which will skip track of the object
origin from _&rl->list[iret + 1]_. I'm not sure whether the behavior was originally intended or not.

2022-04-23 13:10 UTC, jserv commented
@linD026, Please help review this proposed change.

2022-04-23 13:14 UTC, jserv requested changes
Read https://cbea.ms/git-commit/ carefully. Then, write down informative commit message(s).

2022-04-23 16:46 UTC, jserv commented
You should use `git rebase` rather than `git merge`. Then, use `git rebase -i` to squash the commits and force-push.

2022-04-24 08:35 UTC, linD026 commented
In my opinion, it might be a bug.
Since the delete is to move the objects after the `iret` forward one index, it will skip the next object when we increase the `iret` after every time deleted.

2022-04-29 13:06 UTC, kdnvt commented
I think the change is correct since the original code skips the next element if a deletion happens.

2022-04-30 17:09 UTC, merged

2022-04-30 17:09 UTC, jserv commented
Thank @kevinshieh0225 for contributing. The git commit message was amended upon the review of @linD026 and @kdnvt .